# Generated by Django 2.2.3 on 2019-08-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_pokemonelementtype_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='disappeared_at',
            new_name='disappear_at',
        ),
    ]
