# Generated by Django 2.2.3 on 2019-08-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_auto_20190817_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='appear_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Появится в'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappear_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Пропадет в'),
        ),
    ]
